### ISSUE TITLE
Setup MariaDB to work with an external volume

### ISSUE THREAD

**Issue by oserban** [ove/ove-asset-services#34]
Currently it saves the data within the docker image

**Comment by oserban** [comment]
Please note that the docker volume is not deleted when the image is loaded or unloaded. I also tested pruning all the dangling images and network adapters and the volume is not deleted.

**Comment by oserban** [comment]
Sample config to test the mariadb image and it's reliability:

**docker-compose.yml**

```yaml
version: '3'
services:
  ovehub-ove-asset-db:
    image: mariadb
    ports:
    - "3306:3306"
    volumes:
      - "ovehub-ove-asset-db-data:/var/lib/mysql"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "dev_assets"
      MYSQL_USER: "dev_a_m"
      MYSQL_PASSWORD: "long&strongPassword"

volumes:
  ovehub-ove-asset-db-data:
```
